### ISSUE TITLE
ModuleNotFoundError: No module named 'names'

### ISSUE THREAD

**Issue by sam99eer** [rvaidun/Document-Generator#3]
When I try with python command, this error comes
![image](https://user-images.githubusercontent.com/38729951/144740929-3e7d3e53-c507-462c-a30b-8f550e1651f8.png)

When I try with python3 command, this error comes

Please update
![Screenshot_1](https://user-images.githubusercontent.com/38729951/144740956-0ece4a7d-86bf-431a-9f0f-509a56352499.png)

**Comment by afshanmomin-git** [comment]
any fix ?
