### ISSUE TITLE
Fix for windows

### ISSUE THREAD

**Issue by JustAnOkapi** [rvaidun/Document-Generator#5]
everything works with this one change to line  https://github.com/rvaidun/Document-Generator/blob/63373cb7462fd156c8cffe3047d2985d17a817e0/generate_documents.py#L45
 to
 `    document.save("./" + folder + "/" + "".join(i for i in title.strip() if i not in "\/:*?<>|") + ".docx")`

**Comment by Dennisleverant** [comment]
How do I run this? Please let me know
